### ISSUE TITLE
Runtime: compile time Tz database usage emits compiler error

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/next-ls#158]
I assume this is because the app doesn't start so it doesn't download the time zone database, but is run at compile time.

```
== Compilation error in file lib/elixir_tools/extensions/post_extension.ex ==
** (UndefinedFunctionError) function Tz.TimeZoneDatabase.time_zone_periods_from_wall_datetime/2 is undefined (module Tz.TimeZoneDatabase is not available)
    (tz 0.26.2) Tz.TimeZoneDatabase.time_zone_periods_from_wall_datetime(~N[2023-07-05 01:00:00], "America/Indiana/Indianapolis")
    (elixir 1.15.0) lib/calendar/datetime.ex:542: DateTime.from_naive/3
    (elixir 1.15.0) lib/calendar/datetime.ex:658: DateTime.from_naive!/3
    lib/elixir_tools/extensions/post_extension.ex:6: ElixirTools.PostExtension.Post.build/3
    (elixir 1.15.0) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (nimble_publisher 1.0.0) lib/nimble_publisher.ex:41: NimblePublisher.__extract__/2
    lib/elixir_tools/extensions/post_extension.ex:21: (module)
```

## Acceptance Criteria

- [ ] there should be no diagnostic reported
- [ ] no special cases for certain libraries

**Comment by mhanberg** [comment]
I think this was a weird state from me switching back and force between different builds and such
