### ISSUE TITLE
Error starting in vscode: Client is not running and can't be stopped

### ISSUE THREAD

**Issue by aloukissas** [elixir-tools/next-ls#207]
From the output in vscode:

```
[Error - 4:12:02 PM] Client NextLS: connection to server is erroring. Shutting down server.
[Error - 4:12:02 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at _.shutdown (/Users/aloukissas/.vscode/extensions/elixir-tools.elixir-tools-0.8.0/dist/extension.js:2:96701)
	at _.stop (/Users/aloukissas/.vscode/extensions/elixir-tools.elixir-tools-0.8.0/dist/extension.js:2:96282)
	at _.stop (/Users/aloukissas/.vscode/extensions/elixir-tools.elixir-tools-0.8.0/dist/extension.js:2:258296)
	at _.handleConnectionError (/Users/aloukissas/.vscode/extensions/elixir-tools.elixir-tools-0.8.0/dist/extension.js:2:102789)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Running in terminal, I get this:

```~/.cache/elixir-tools/nextls/bin/nextls --port 9000

16:11:42.275 [notice] Protocol 'inet_tcp': register/listen error: econnrefused

Starting on port 9000
```

Is the `econnrefused` a red herring?

**Comment by aloukissas** [comment]
This looks like it's related to #186. Also, my .tool-versions:

```
erlang 25.3.2.5
elixir 1.15.4-otp-25
```

**Comment by mhanberg** [comment]
You need run `epmd -daemon`. 

That's what the inet_tcp error is about.

**Comment by mhanberg** [comment]
https://github.com/elixir-tools/next-ls/issues/204

**Comment by mhanberg** [comment]
@aloukissas did starting epmd solve the problem? if yes, i'll close this issue as a duplicate

**Comment by mhanberg** [comment]
@aloukissas Ping

**Comment by benregn** [comment]
I had the exact same error in my NextLS output in VSCode and running `epmd -daemon` fixed it 👍

**Comment by mhanberg** [comment]
The current latest release will attempt to start epmd when NextLS boots, so I will close this and can re-open if the issue appears again. 

Thanks @benregn

**Comment by benregn** [comment]
Thank you and keep up the good work!
