### ISSUE TITLE
Mint.TransportError when building with flake

### ISSUE THREAD

**Issue by zdcthomas** [elixir-tools/next-ls#243]
Hello!

I saw that this repo has a `flake.nix` and I wanted to try to incorporate it as a package into a devShell, but I keep running into the same build error

My flake looks like this 
```nix
{
  inputs = {
    next-ls = {
      url = "github:elixir-tools/next-ls";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs = {
      url = "github:NixOS/nixpkgs";
    };

    systems.url = "github:nix-systems/default";
  };

  outputs = {
    self,
    nixpkgs,
    systems,
    flake-utils,
    next-ls,
  }:
    flake-utils.lib.eachSystem (import systems)
    (
      system: let
        pkgs = import nixpkgs {
          inherit system;
        };
      in rec {
        devShells.default = pkgs.mkShell {
          packages = [
            next-ls.packages.${system}.default
          ];
        };
      }
    );
}
```
and my flake.lock looks like this 
```json
{
  "nodes": {
    "flake-utils": {
      "inputs": {
        "systems": "systems"
      },
      "locked": {
        "lastModified": 1694529238,
        "narHash": "sha256-zsNZZGTGnMOf9YpHKJqMSsa0dXbfmxeoJ7xHlrt+xmY=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "ff7b65b44d01cf9ba6a71320833626af21126384",
        "type": "github"
      },
      "original": {
        "id": "flake-utils",
        "type": "indirect"
      }
    },
    "next-ls": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1695317112,
        "narHash": "sha256-NEpyDcpFjG50L6ZeSkHzCrQstD9kgRqMdEXIrR37tFE=",
        "owner": "elixir-tools",
        "repo": "next-ls",
        "rev": "b0de52689b51544fb2e1f0a49b3eace28a5de732",
        "type": "github"
      },
      "original": {
        "owner": "elixir-tools",
        "ref": "v0.12.6",
        "repo": "next-ls",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1693535723,
        "narHash": "sha256-ERFGB4HsvW4MASfaiYa5KDpaMc6US4FgK5KAYROCsbg=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "76ae447f06e8be22c1adba3d979bcf5a3b7b14b9",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "flake-utils": "flake-utils",
        "next-ls": "next-ls",
        "nixpkgs": "nixpkgs",
        "systems": "systems_2"
      }
    },
    "systems": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    },
    "systems_2": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    }
  },
  "root": "root",
  "version": 7
}
```
Here's the error I'm getting

```
error: builder for '/nix/store/kjgrgzj82b7bnhvffw6hfhjb1zw67r66-next-ls-0.12.6.drv' failed with exit code 1;
       last 10 log lines:
       > 18:04:16.927 [error] ** (Mint.TransportError) non-existing domain
       > ** (Mint.TransportError) non-existing domain
       >     (req 0.3.11) lib/req.ex:379: Req.get!/2
       >     (burrito 0.8.0) lib/util/default_erts_resolver.ex:88: Burrito.Util.DefaultERTSResolver.do_download/2
       >     (burrito 0.8.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
       >     (burrito 0.8.0) lib/steps/fetch/resolve_erts.ex:34: Burrito.Steps.Fetch.ResolveERTS.execute/1
       >     (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
       >     (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       >     (elixir 1.15.4) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
       >     (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
       For full logs, run 'nix log /nix/store/kjgrgzj82b7bnhvffw6hfhjb1zw67r66-next-ls-0.12.6.drv'.
error: 1 dependencies of derivation '/nix/store/4brif62yl8lybnqmybn8cwff656g85gy-nix-shell-env.drv' failed to build
error: getting status of '/home/zdcthomas/dev/resume/.direnv/flake-profile.403477': No such file or directory
warning: Git tree '/home/zdcthomas/dev/resume' is dirty
```
Thanks so much for all the dev work! Super excited to try this out!

**Comment by zdcthomas** [comment]
I'm on x86_64-linux running NIXOS as well.

**Comment by zdcthomas** [comment]
I've also tried specifying with the most recent tag in the url

**Comment by mhanberg** [comment]
Known issue, someone is already fixing it, just waiting on a fix in one of our dependencies

**Comment by zdcthomas** [comment]
Just saw the comment on [the `announcement](https://www.elixir-tools.dev/news/the-elixir-tools-update-vol-3/) about this not working on nixos yet. I'll take a crack at it!

**Comment by zdcthomas** [comment]
Ah gotcha, which dependency? maybe I can help out

**Comment by mhanberg** [comment]
Just need this to get merged https://github.com/burrito-elixir/burrito/pull/105

**Comment by mhanberg** [comment]
> Thanks so much for all the dev work! Super excited to try this out!

I missed this earlier, you're welcome! And thank you for being an early adopter 😎

**Comment by mhanberg** [comment]
Should be fixed
