### ISSUE TITLE
Failed to build with burrito on macOS Sonoma (nix-darwin)

### ISSUE THREAD

**Issue by zoedsoupe** [elixir-tools/next-ls#249]
complete error:
```sh
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/l2iq5fcx0p48h2v738mgx34h413by2nm-next-ls-0.12.6.drv^*'
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/1wg0yy51y1g7gdcscqiqam261sl0na4g-l8grv4p8d319hsdbksr>
source root is l8grv4p8d319hsdbksr462bz65vc6nmq-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
==> typed_struct
Compiling 2 files (.ex)
Generated typed_struct app
==> mime
Compiling 1 file (.ex)
Generated mime app
==> nimble_options
Compiling 3 files (.ex)
Generated nimble_options app
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
...skipping...
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
Compiling 21 files (.ex)
Generated next_ls app
@nix { "action": "setPhase", "phase": "installPhase" }
installing
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash: warning: setlocale: L>
/nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/sh: warning: setlocale: LC_>
* assembling next_ls-0.12.6 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
* skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)
> Target is being overridden with BURRITO_TARGET darwin_arm64
> Burrito is building target: darwin_arm64
> Burrito will build for target:
        OS: darwin
        CPU: aarch64
        Qualifiers: [libc: nil]
        Debug: false
----> PHASE: :fetch
--> Working directory: /private/tmp/nix-build-next-ls-0.12.6.drv-0/burrito_build_77B7F51>
--> Resolving ERTS: {:local_unpacked, [path: "/nix/store/9hi9qmhvrzy10ph469c7d5z59xdjk4v>
----> PHASE: :patch
--> Replacing ERTS binaries...
----> PHASE: :build
--> Generating wrapper metadata file...
Semantic Analysis [3199] mulWide... Semantic Analysis [3365] allocatedSlice... Semantic >
error: UndefinedSymbolReference
--> Cleaning up...
--> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBui>
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_ph>
    (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.15.6) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.6) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.6) lib/mix/cli.ex:92: Mix.CLI.run_task/2
```

**Comment by mhanberg** [comment]
I haven't tried Sonoma yet, I'll have to update and give it a spin

**Comment by mhanberg** [comment]
I was able to reproduce after updating to sonoma. 

I think this is unrelated to Nix, just fails to build on sonoma

**Comment by mhanberg** [comment]
This shouldn't impact usage, as the published binaries are built with macOS 13. It should only impact if you are building a prod release from source. 

I need to get a nix binary cache setup and it should help with this

**Comment by mhanberg** [comment]
The burrito patch has been merged, i just need to bump it in next ls and cut a release
