### ISSUE TITLE
Task terminating

### ISSUE THREAD

**Issue by tcoopman** [elixir-tools/next-ls#300]
I wanted to test out next-ls in helix, but I can't seem to get it to work, this is what I get in my logs:

```
2023-10-25T15:36:59.573 helix_lsp::transport [ERROR] nextls err: <- StreamClosed
2023-10-25T15:37:02.285 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "15:37:02.169 [error] Task #PID<0.215.0> started from #PID<0.193.0> terminating\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "** (stop) exited in: GenServer.call(#PID<0.205.0>, {:compile, [force: false]}, :infinity)\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    ** (EXIT) shutdown: :nodedown\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    (elixir 1.15.6) lib/gen_server.ex:1074: GenServer.call/3\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    (next_ls 0.14.1) lib/next_ls.ex:880: anonymous fn/3 in NextLS.handle_info/2\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    (elixir 1.15.6) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    (elixir 1.15.6) lib/task/supervised.ex:36: Task.Supervised.reply/4\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "Function: #Function<1.27393220/0 in NextLS.handle_info/2>\n"
2023-10-25T15:37:02.285 helix_lsp::transport [ERROR] nextls err <- "    Args: []\n"
```

**Comment by mhanberg** [comment]
Hmm, that message should have been printed to stderr, which helix should be ignoring.

I'll try to reproduce to confirm my suspicion.

Thanks for the report!

**Comment by tcoopman** [comment]
If you have anything you want me to try let me know
