### ISSUE TITLE
burrito error compiling 0.16.0

### ISSUE THREAD

**Issue by 1player** [elixir-tools/next-ls#359]
I've updated the Archlinux AUR config to try out 0.16.0, which fails with:

```
==> next_ls
Compiling 26 files (.ex)
Generated next_ls app
* assembling next_ls-0.16.0 on MIX_ENV=prod
* using config/runtime.exs to configure the release at runtime
* skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)
> Target is being overridden with BURRITO_TARGET linux_amd64
> Burrito is building target: linux_amd64
> Burrito will build for target:
        OS: linux
        CPU: x86_64
        Qualifiers: [libc: :gnu]
        Debug: false
----> PHASE: :fetch
--> Working directory: /tmp/burrito_build_9790ACE94CB524F2
--> Resolving ERTS: {:precompiled, [version: "26.2.1"]}
--> Remote ERTS From Beam Machine: https://burrito-otp.b-cdn.net/OTP-26.2.1/linux/x86_64/gnu/otp_26.2.1_linux_gnu_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://burrito-otp.b-cdn.net/OTP-26.2.1/linux/x86_64/gnu/otp_26.2.1_linux_gnu_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://burrito-otp.b-cdn.net/OTP-26.2.1/linux/x86_64/gnu/otp_26.2.1_linux_gnu_x86_64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
    (burrito 0.8.0) lib/util/default_erts_resolver.ex:40: Burrito.Util.DefaultERTSResolver.do_resolve/1
    (burrito 0.8.0) lib/steps/fetch/resolve_erts.ex:34: Burrito.Steps.Fetch.ResolveERTS.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.16.0) lib/mix/tasks/release.ex:1076: Mix.Tasks.Release.run_steps/1
```

**Comment by mhanberg** [comment]
I believe i i need to migrate from burrito on github to v1.0 on hex

**Comment by mhanberg** [comment]
So the main problem is that the precompiled OTP is not available for that version. if you use the version specified in the .mise.toml file, it should work. it worked for the release i did last night

**Comment by 1player** [comment]
I just tried to update burrito to 1.0 and that seemed to do the trick. Now the issue is that there are a ton of failing tests, so I'm not sure whether v0.16.1..HEAD is broken, if it's due to upgrading burrito, or something else. Back to elixir-ls I go...

**Comment by mhanberg** [comment]
I'll try today.

**Comment by mhanberg** [comment]
seems to work on my end, just need to figure out some stuff with the nix flake. will get it patched and pushed here soon
