### ISSUE TITLE
Request textDocument/formatting failed.

### ISSUE THREAD

**Issue by apoorv-2204** [elixir-tools/next-ls#554]
```elixir
 Error - 19:30:00] ** (BadMapError) expected a map, got: :timeout
  (stdlib 6.0) :maps.merge(%{}, :timeout)
  (next_ls 0.23.2) lib/next_ls.ex:983: anonymous fn/2 in NextLS.handle_notification/2
  (elixir 1.17.2) lib/map.ex:916: Map.update!/3
  (next_ls 0.23.2) lib/next_ls.ex:983: NextLS.handle_notification/2
  (gen_lsp 0.10.0) lib/gen_lsp.ex:478: anonymous fn/2 in GenLSP.loop/3
  (telemetry 1.2.1) /Users/runner/work/next-ls/next-ls/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
  (gen_lsp 0.10.0) lib/gen_lsp.ex:474: anonymous fn/7 in GenLSP.loop/3
  (gen_lsp 0.10.0) lib/gen_lsp.ex:553: GenLSP.attempt/4

**Comment by mhanberg** [comment]
Closed by #569
