### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-tools/next-ls#556]
I get this error on one project for pretty much every function in the project. unsure what exactly i'm doing wrong, but `{:error :module_not_found}` seems important. happy to share what i can

```
Request textDocument/hover failed.
  Message: ** (MatchError) no match of right hand side value: [ok: {:docs_v1, 1, :elixir, "text/markdown", :none, %{}, [{{:function, :create_reminder, 1}, 24, ["create_reminder(args)"], :none, %{}}, {{:function, :list_reminders, 0}, 38, ["list_reminders()"], :none, %{}}, {{:function, :parse_message, 2}, 45, ["parse_message(message, regex)"], :none, %{}}, {{:function, :update_reminder, 2}, 31, ["update_reminder(reminder, now)"], :none, %{}}, {{:type, :time_unit, 0}, 5, [], :none, %{}}, {{:type, :create_attrs, 0}, 7, [], :none, %{}}, {{:type, :base_attrs, 0}, 15, [], :none, %{}}]}, ok: {:error, :module_not_found}]
    (next_ls 0.23.2) lib/next_ls.ex:377: anonymous fn/3 in NextLS.handle_request/2
    (next_ls 0.23.2) lib/next_ls.ex:1339: anonymous fn/4 in NextLS.dispatch/3
    (elixir 1.17.2) lib/registry.ex:488: Registry.dispatch/4
    (next_ls 0.23.2) lib/next_ls.ex:1338: NextLS.dispatch/3
    (next_ls 0.23.2) lib/next_ls.ex:376: NextLS.handle_request/2
    (gen_lsp 0.10.0) lib/gen_lsp.ex:350: anonymous fn/2 in GenLSP.loop/3
    (telemetry 1.2.1) /Users/runner/work/next-ls/next-ls/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (gen_lsp 0.10.0) lib/gen_lsp.ex:349: anonymous fn/7 in GenLSP.loop/3
```

**Comment by mhanberg** [comment]
Are you using workspace folders with this project?
